[package]
name = "temp_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.15.0"
num-traits = "0.2.15"
rand = "0.8.5"
ash = "0.37.2+1.3.238"
vulkano-shaders = "0.32.0"
itertools = "0.10.5"
glam = "0.23.0"
memoffset = "0.8.0"
image = {version="0.24.4", features=["default"]}